# 站点配置

# 导入主题
theme: jekyll-theme-chirpy

# 网页语言设置 › http://www.lingoes.net/en/translator/langcode.htm
# 如果与`_data/locales`文件夹中的文件名相同，布局语言也会相应改变，
# 否则将使用默认的'en'值
lang: zh-CN

# 更改为您的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: xbsbcb's blog # 主标题

tagline: Hello World! # 显示为副标题

description: >- # 用于SEO元数据和Atom订阅
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# 填写您的站点协议和主机名
# 例如：'https://username.github.io'，注意不要以'/'结尾
url: "https://xbsbcb.github.io"

github:
  username: xbsbcb # 更改为您的GitHub用户名

twitter:
  username: xxxxx # 更改为您的Twitter用户名

social:
  # 更改为您的全名
  # 将作为文章的默认作者和页脚的版权所有者
  name: TianZhibo
  email: xbsbcb@gmail.com # 更改为您的邮箱地址
  links:
    # 第一个链接将作为版权所有者的链接
    - https://twitter.com/username # 更改为您的Twitter主页
    - https://github.com/username # 更改为您的GitHub主页
    # 取消注释以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 网站验证设置
webmaster_verifications:
  google: # 填写Google验证码
  bing: # 填写Bing验证码
  alexa: # 填写Alexa验证码
  yandex: # 填写Yandex验证码
  baidu: # 填写Baidu验证码
  facebook: # 填写Facebook验证码

# ↑ --------------------------
# jekyll-seo-tag 设置结束

# 网站分析设置
analytics:
  google:
    id: # 填写Google Analytics ID
  goatcounter:
    id: # 填写GoatCounter ID
  umami:
    id: # 填写Umami ID
    domain: # 填写Umami域名
  matomo:
    id: # 填写Matomo ID
    domain: # 填写Matomo域名
  cloudflare:
    id: # 填写Cloudflare网站分析令牌
  fathom:
    id: # 填写Fathom站点ID

# 页面浏览统计设置
pageviews:
  provider: # 目前仅支持'goatcounter'

# 主题颜色偏好设置
#
# 注意：保持空值将默认跟随系统配色，
# 侧边栏左下方会有切换深色/浅色主题的开关
#
# 可用选项：
#     light — 使用浅色主题
#     dark — 使用深色主题
#
theme_mode: # [light | dark]

# 媒体资源的CDN端点
# 设置后，所有以'/'开头的媒体资源路径（站点头像、文章图片、音视频文件）
# 都将添加该CDN地址
#
# 例如：'https://cdn.com'
cdn:

# 侧边栏头像，支持本地或CORS资源
avatar: assets/img/avatar.jpg

# 全站社交媒体预览图片URL，用于SEO的og:image元标签
# 可通过文章front matter中的page.image覆盖
social_preview_image: # 字符串，本地或CORS资源

# 布尔值，控制文章目录的全局开关
toc: true

comments:
  # 评论系统的全局开关，保持空值表示禁用
  provider: # [disqus | utterances | giscus]
  # 各评论提供商配置：
  disqus:
    shortname: # 填写Disqus短名称 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances设置 › https://utteranc.es/
  utterances:
    repo: # <GitHub用户名>/<仓库名>
    issue_term: # < url | pathname | title | ...>
  # Giscus选项 › https://giscus.app
  giscus:
    repo: # <GitHub用户名>/<仓库名>
    repo_id:
    category:
    category_id:
    mapping: # 可选，默认为'pathname'
    strict: # 可选，默认为'0'
    input_position: # 可选，默认为'bottom'
    lang: # 可选，默认使用`site.lang`的值
    reactions_enabled: # 可选，默认为'1'

# 自托管静态资源，可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值，保持空值表示false
    # 指定Jekyll环境，空值表示全部环境
    # 仅在`assets.self_host.enabled`为'true'时生效
    env: # [development | production]

# ... 后续配置保持原有注释翻译模式 ...